version: 1
services:
  - type: web
    name: XBug-Bot
    env: node
    buildCommand: "npm install"
    startCommand: "node index.js"
    plan: free
    autoDeploy: true
    envVars:
      - key: API_KEY
        value: rnd_Y02vyyHu2Zsdhx0yTQl0xblw6i2j  # Votre clé API
